# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T10:41:47+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity
from fastapi import Header, Path, Query
from pydantic import conint, constr

from models import (
    AccessDeniedException,
    CompleteSnapshotResponse,
    ConcurrentLimitExceededException,
    ConflictException,
    GetSnapshotBlockResponse,
    InternalServerException,
    ListChangedBlocksResponse,
    ListSnapshotBlocksResponse,
    PutSnapshotBlockResponse,
    RequestThrottledException,
    ResourceNotFoundException,
    ServiceQuotaExceededException,
    SnapshotsPostRequest,
    SnapshotsSnapshotIdBlocksBlockIndexXAmzDataLengthXAmzChecksumXAmzChecksumAlgorithmPutRequest,
    StartSnapshotResponse,
    ValidationException,
    XAmzChecksumAggregationMethod,
    XAmzChecksumAlgorithm,
)

app = MCPProxy(
    contact={
        'email': 'mike.ralphson@gmail.com',
        'name': 'Mike Ralphson',
        'url': 'https://github.com/mermade/aws2openapi',
        'x-twitter': 'PermittedSoc',
    },
    description='<p>You can use the Amazon Elastic Block Store (Amazon EBS) direct APIs to create Amazon EBS snapshots, write data directly to your snapshots, read data on your snapshots, and identify the differences or changes between two snapshots. If you’re an independent software vendor (ISV) who offers backup services for Amazon EBS, the EBS direct APIs make it more efficient and cost-effective to track incremental changes on your Amazon EBS volumes through snapshots. This can be done without having to create new volumes from snapshots, and then use Amazon Elastic Compute Cloud (Amazon EC2) instances to compare the differences.</p> <p>You can create incremental snapshots directly from data on-premises into volumes and the cloud to use for quick disaster recovery. With the ability to write and read snapshots, you can write your on-premises data to an snapshot during a disaster. Then after recovery, you can restore it back to Amazon Web Services or on-premises from the snapshot. You no longer need to build and maintain complex mechanisms to copy data to and from Amazon EBS.</p> <p>This API reference provides detailed information about the actions, data types, parameters, and errors of the EBS direct APIs. For more information about the elements that make up the EBS direct APIs, and examples of how to use them effectively, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-accessing-snapshot.html">Accessing the Contents of an Amazon EBS Snapshot</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>. For more information about the supported Amazon Web Services Regions, endpoints, and service quotas for the EBS direct APIs, see <a href="https://docs.aws.amazon.com/general/latest/gr/ebs-service.html">Amazon Elastic Block Store Endpoints and Quotas</a> in the <i>Amazon Web Services General Reference</i>.</p>',
    license={'name': 'Apache 2.0 License', 'url': 'http://www.apache.org/licenses/'},
    termsOfService='https://aws.amazon.com/service-terms/',
    title='Amazon Elastic Block Store',
    version='2019-11-02',
    servers=[
        {
            'description': 'The Amazon EBS multi-region endpoint',
            'url': 'http://ebs.{region}.amazonaws.com',
            'variables': {
                'region': {
                    'default': 'us-east-1',
                    'description': 'The AWS region',
                    'enum': [
                        'us-east-1',
                        'us-east-2',
                        'us-west-1',
                        'us-west-2',
                        'us-gov-west-1',
                        'us-gov-east-1',
                        'ca-central-1',
                        'eu-north-1',
                        'eu-west-1',
                        'eu-west-2',
                        'eu-west-3',
                        'eu-central-1',
                        'eu-south-1',
                        'af-south-1',
                        'ap-northeast-1',
                        'ap-northeast-2',
                        'ap-northeast-3',
                        'ap-southeast-1',
                        'ap-southeast-2',
                        'ap-east-1',
                        'ap-south-1',
                        'sa-east-1',
                        'me-south-1',
                    ],
                }
            },
        },
        {
            'description': 'The Amazon EBS multi-region endpoint',
            'url': 'https://ebs.{region}.amazonaws.com',
            'variables': {
                'region': {
                    'default': 'us-east-1',
                    'description': 'The AWS region',
                    'enum': [
                        'us-east-1',
                        'us-east-2',
                        'us-west-1',
                        'us-west-2',
                        'us-gov-west-1',
                        'us-gov-east-1',
                        'ca-central-1',
                        'eu-north-1',
                        'eu-west-1',
                        'eu-west-2',
                        'eu-west-3',
                        'eu-central-1',
                        'eu-south-1',
                        'af-south-1',
                        'ap-northeast-1',
                        'ap-northeast-2',
                        'ap-northeast-3',
                        'ap-southeast-1',
                        'ap-southeast-2',
                        'ap-east-1',
                        'ap-south-1',
                        'sa-east-1',
                        'me-south-1',
                    ],
                }
            },
        },
        {
            'description': 'The Amazon EBS endpoint for China (Beijing) and China (Ningxia)',
            'url': 'http://ebs.{region}.amazonaws.com.cn',
            'variables': {
                'region': {
                    'default': 'cn-north-1',
                    'description': 'The AWS region',
                    'enum': ['cn-north-1', 'cn-northwest-1'],
                }
            },
        },
        {
            'description': 'The Amazon EBS endpoint for China (Beijing) and China (Ningxia)',
            'url': 'https://ebs.{region}.amazonaws.com.cn',
            'variables': {
                'region': {
                    'default': 'cn-north-1',
                    'description': 'The AWS region',
                    'enum': ['cn-north-1', 'cn-northwest-1'],
                }
            },
        },
    ],
)


@app.post(
    '/snapshots',
    description=""" <p>Creates a new Amazon EBS snapshot. The new snapshot enters the <code>pending</code> state after the request completes. </p> <p>After creating the snapshot, use <a href="https://docs.aws.amazon.com/ebs/latest/APIReference/API_PutSnapshotBlock.html"> PutSnapshotBlock</a> to write blocks of data to the snapshot.</p> """,
    tags=['snapshot_management', 'snapshot_block_handling'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def start_snapshot(
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: SnapshotsPostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/snapshots/completion/{snapshotId}#x-amz-ChangedBlocksCount',
    description=""" Seals and completes the snapshot after all of the required blocks of data have been written to it. Completing the snapshot changes the status to <code>completed</code>. You cannot write new blocks to a snapshot after it has been completed. """,
    tags=['snapshot_management', 'snapshot_block_handling'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def complete_snapshot(
    snapshot_id: constr(
        pattern=r'^snap-[0-9a-f]+$', min_length=1, max_length=64
    ) = Path(..., alias='snapshotId'),
    x_amz__changed_blocks_count: conint(ge=0) = Header(
        ..., alias='x-amz-ChangedBlocksCount'
    ),
    x_amz__checksum: Optional[
        constr(pattern=r'^[A-Za-z0-9+/=]+$', max_length=64)
    ] = Header(None, alias='x-amz-Checksum'),
    x_amz__checksum__algorithm: Optional[XAmzChecksumAlgorithm] = Header(
        None, alias='x-amz-Checksum-Algorithm'
    ),
    x_amz__checksum__aggregation__method: Optional[
        XAmzChecksumAggregationMethod
    ] = Header(None, alias='x-amz-Checksum-Aggregation-Method'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/snapshots/{secondSnapshotId}/changedblocks',
    description=""" Returns information about the blocks that are different between two Amazon Elastic Block Store snapshots of the same volume/snapshot lineage. """,
    tags=['snapshot_management', 'snapshot_block_handling'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def list_changed_blocks(
    first_snapshot_id: Optional[
        constr(pattern=r'^snap-[0-9a-f]+$', min_length=1, max_length=64)
    ] = Query(None, alias='firstSnapshotId'),
    second_snapshot_id: constr(
        pattern=r'^snap-[0-9a-f]+$', min_length=1, max_length=64
    ) = Path(..., alias='secondSnapshotId'),
    page_token: Optional[constr(pattern=r'^[A-Za-z0-9+/=]+$', max_length=256)] = Query(
        None, alias='pageToken'
    ),
    max_results: Union[
        Optional[conint(ge=100, le=10000)], Optional[str], Optional[str], Optional[str]
    ] = Query(None, alias='maxResults'),
    starting_block_index: Optional[conint(ge=0)] = Query(
        None, alias='startingBlockIndex'
    ),
    next_token: Optional[str] = Query(None, alias='NextToken'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/snapshots/{snapshotId}/blocks',
    description=""" Returns information about the blocks in an Amazon Elastic Block Store snapshot. """,
    tags=['snapshot_management', 'snapshot_block_handling'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def list_snapshot_blocks(
    snapshot_id: constr(
        pattern=r'^snap-[0-9a-f]+$', min_length=1, max_length=64
    ) = Path(..., alias='snapshotId'),
    page_token: Optional[constr(pattern=r'^[A-Za-z0-9+/=]+$', max_length=256)] = Query(
        None, alias='pageToken'
    ),
    max_results: Union[
        Optional[conint(ge=100, le=10000)], Optional[str], Optional[str], Optional[str]
    ] = Query(None, alias='maxResults'),
    starting_block_index: Optional[conint(ge=0)] = Query(
        None, alias='startingBlockIndex'
    ),
    next_token: Optional[str] = Query(None, alias='NextToken'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/snapshots/{snapshotId}/blocks/{blockIndex}#blockToken',
    description=""" Returns the data in a block in an Amazon Elastic Block Store snapshot. """,
    tags=['snapshot_management', 'snapshot_block_handling'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def get_snapshot_block(
    snapshot_id: constr(
        pattern=r'^snap-[0-9a-f]+$', min_length=1, max_length=64
    ) = Path(..., alias='snapshotId'),
    block_index: conint(ge=0) = Path(..., alias='blockIndex'),
    block_token: constr(pattern=r'^[A-Za-z0-9+/=]+$', max_length=256) = Query(
        ..., alias='blockToken'
    ),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/snapshots/{snapshotId}/blocks/{blockIndex}#x-amz-Data-Length&x-amz-Checksum&x-amz-Checksum-Algorithm',
    description=""" <p>Writes a block of data to a snapshot. If the specified block contains data, the existing data is overwritten. The target snapshot must be in the <code>pending</code> state.</p> <p>Data written to a snapshot must be aligned with 512-KiB sectors.</p> """,
    tags=['snapshot_management', 'snapshot_block_handling'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def put_snapshot_block(
    snapshot_id: constr(
        pattern=r'^snap-[0-9a-f]+$', min_length=1, max_length=64
    ) = Path(..., alias='snapshotId'),
    block_index: conint(ge=0) = Path(..., alias='blockIndex'),
    x_amz__data__length: int = Header(..., alias='x-amz-Data-Length'),
    x_amz__progress: Optional[conint(ge=0, le=100)] = Header(
        None, alias='x-amz-Progress'
    ),
    x_amz__checksum: constr(pattern=r'^[A-Za-z0-9+/=]+$', max_length=64) = Header(
        ..., alias='x-amz-Checksum'
    ),
    x_amz__checksum__algorithm: XAmzChecksumAlgorithm = Header(
        ..., alias='x-amz-Checksum-Algorithm'
    ),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: SnapshotsSnapshotIdBlocksBlockIndexXAmzDataLengthXAmzChecksumXAmzChecksumAlgorithmPutRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
