# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T10:41:47+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field, RootModel, SecretStr, conint, constr


class AccessDeniedException(RootModel[Any]):
    root: Any


class BlockData(RootModel[SecretStr]):
    root: SecretStr


class BlockIndex(RootModel[conint(ge=0)]):
    root: conint(ge=0)


class BlockSize(RootModel[int]):
    root: int


class BlockToken(RootModel[constr(pattern=r'^[A-Za-z0-9+/=]+$', max_length=256)]):
    root: constr(pattern=r'^[A-Za-z0-9+/=]+$', max_length=256)


class Boolean(RootModel[bool]):
    root: bool


class ChangedBlock(BaseModel):
    BlockIndex_1: Optional[BlockIndex] = Field(None, alias='BlockIndex')
    FirstBlockToken: Optional[BlockToken] = None
    SecondBlockToken: Optional[BlockToken] = None


class ChangedBlocks(RootModel[List[ChangedBlock]]):
    root: List[ChangedBlock]


class ChangedBlocksCount(RootModel[conint(ge=0)]):
    root: conint(ge=0)


class Checksum(RootModel[constr(pattern=r'^[A-Za-z0-9+/=]+$', max_length=64)]):
    root: constr(pattern=r'^[A-Za-z0-9+/=]+$', max_length=64)


class ChecksumAggregationMethod(Enum):
    LINEAR = 'LINEAR'


class ChecksumAlgorithm(Enum):
    SHA256 = 'SHA256'


class CompleteSnapshotRequest(BaseModel):
    pass


class ConcurrentLimitExceededException(RootModel[Any]):
    root: Any


class ConflictException(RootModel[Any]):
    root: Any


class DataLength(RootModel[int]):
    root: int


class Description(RootModel[constr(pattern=r'^[\S\s]+$', max_length=255)]):
    root: constr(pattern=r'^[\S\s]+$', max_length=255)


class GetSnapshotBlockRequest(BaseModel):
    pass


class GetSnapshotBlockResponse(BaseModel):
    BlockData_1: Optional[BlockData] = Field(None, alias='BlockData')


class IdempotencyToken(RootModel[constr(pattern=r'^[\S]+$', max_length=255)]):
    root: constr(pattern=r'^[\S]+$', max_length=255)


class InternalServerException(RootModel[Any]):
    root: Any


class KmsKeyArn(RootModel[SecretStr]):
    root: SecretStr


class ListChangedBlocksRequest(BaseModel):
    pass


class ListSnapshotBlocksRequest(BaseModel):
    pass


class MaxResults(RootModel[conint(ge=100, le=10000)]):
    root: conint(ge=100, le=10000)


class OwnerId(RootModel[constr(pattern=r'\S+', min_length=1, max_length=24)]):
    root: constr(pattern=r'\S+', min_length=1, max_length=24)


class PageToken(RootModel[constr(pattern=r'^[A-Za-z0-9+/=]+$', max_length=256)]):
    root: constr(pattern=r'^[A-Za-z0-9+/=]+$', max_length=256)


class Progress(RootModel[conint(ge=0, le=100)]):
    root: conint(ge=0, le=100)


class PutSnapshotBlockRequest(BaseModel):
    BlockData_1: BlockData = Field(..., alias='BlockData')


class PutSnapshotBlockResponse(BaseModel):
    pass


class RequestThrottledException(RootModel[Any]):
    root: Any


class ResourceNotFoundException(RootModel[Any]):
    root: Any


class ServiceQuotaExceededException(RootModel[Any]):
    root: Any


class SnapshotId(
    RootModel[constr(pattern=r'^snap-[0-9a-f]+$', min_length=1, max_length=64)]
):
    root: constr(pattern=r'^snap-[0-9a-f]+$', min_length=1, max_length=64)


class Status(Enum):
    completed = 'completed'
    pending = 'pending'
    error = 'error'


class TagKey(RootModel[constr(pattern=r'^[\S\s]+$', max_length=127)]):
    root: constr(pattern=r'^[\S\s]+$', max_length=127)


class TagValue(RootModel[constr(pattern=r'^[\S\s]*$', max_length=255)]):
    root: constr(pattern=r'^[\S\s]*$', max_length=255)


class TimeStamp(RootModel[datetime]):
    root: datetime


class Timeout(RootModel[conint(ge=10, le=4320)]):
    root: conint(ge=10, le=4320)


class ValidationException(RootModel[Any]):
    root: Any


class VolumeSize(RootModel[conint(ge=1)]):
    root: conint(ge=1)


class XAmzChecksumAlgorithm(Enum):
    SHA256 = 'SHA256'


class XAmzChecksumAggregationMethod(Enum):
    LINEAR = 'LINEAR'


class SnapshotsSnapshotIdBlocksBlockIndexXAmzDataLengthXAmzChecksumXAmzChecksumAlgorithmPutRequest(
    BaseModel
):
    BlockData: SecretStr = Field(
        ...,
        description='<p>The data to write to the block.</p> <p>The block data is not signed as part of the Signature Version 4 signing process. As a result, you must generate and provide a Base64-encoded SHA256 checksum for the block data using the <b>x-amz-Checksum</b> header. Also, you must specify the checksum algorithm using the <b>x-amz-Checksum-Algorithm</b> header. The checksum that you provide is part of the Signature Version 4 signing process. It is validated against a checksum generated by Amazon EBS to ensure the validity and authenticity of the data. If the checksums do not correspond, the request fails. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-accessing-snapshot.html#ebsapis-using-checksums"> Using checksums with the EBS direct APIs</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p>',
    )


class Block(BaseModel):
    BlockIndex_1: Optional[BlockIndex] = Field(None, alias='BlockIndex')
    BlockToken_1: Optional[BlockToken] = Field(None, alias='BlockToken')


class Blocks(RootModel[List[Block]]):
    root: List[Block]


class CompleteSnapshotResponse(BaseModel):
    Status_1: Optional[Status] = Field(None, alias='Status')


class ListChangedBlocksResponse(BaseModel):
    BlockSize_1: Optional[BlockSize] = Field(None, alias='BlockSize')
    ChangedBlocks_1: Optional[ChangedBlocks] = Field(None, alias='ChangedBlocks')
    ExpiryTime: Optional[TimeStamp] = None
    NextToken: Optional[PageToken] = None
    VolumeSize_1: Optional[VolumeSize] = Field(None, alias='VolumeSize')


class ListSnapshotBlocksResponse(BaseModel):
    BlockSize_1: Optional[BlockSize] = Field(None, alias='BlockSize')
    Blocks_1: Optional[Blocks] = Field(None, alias='Blocks')
    ExpiryTime: Optional[TimeStamp] = None
    NextToken: Optional[PageToken] = None
    VolumeSize_1: Optional[VolumeSize] = Field(None, alias='VolumeSize')


class Tag(BaseModel):
    Key: Optional[TagKey] = None
    Value: Optional[TagValue] = None


class Tags(RootModel[List[Tag]]):
    root: List[Tag]


class SnapshotsPostRequest(BaseModel):
    ClientToken: Optional[constr(pattern=r'^[\S]+$', max_length=255)] = Field(
        None,
        description='<p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully. The subsequent retries with the same client token return the result from the original successful request and they have no additional effect.</p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p> <p>For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-direct-api-idempotency.html"> Idempotency for StartSnapshot API</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p>',
    )
    Description: Optional[constr(pattern=r'^[\S\s]+$', max_length=255)] = Field(
        None, description='A description for the snapshot.'
    )
    Encrypted: Optional[bool] = Field(
        None,
        description='<p>Indicates whether to encrypt the snapshot.</p> <p>You can\'t specify <b>Encrypted</b> and <b> ParentSnapshotId</b> in the same request. If you specify both parameters, the request fails with <code>ValidationException</code>.</p> <p>The encryption status of the snapshot depends on the values that you specify for <b>Encrypted</b>, <b>KmsKeyArn</b>, and <b>ParentSnapshotId</b>, and whether your Amazon Web Services account is enabled for <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#encryption-by-default"> encryption by default</a>. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebsapis-using-encryption.html"> Using encryption</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p> <important> <p>To create an encrypted snapshot, you must have permission to use the KMS key. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebsapi-permissions.html#ebsapi-kms-permissions"> Permissions to use Key Management Service keys</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p> </important>',
    )
    KmsKeyArn: Optional[SecretStr] = Field(
        None,
        description='<p>The Amazon Resource Name (ARN) of the Key Management Service (KMS) key to be used to encrypt the snapshot.</p> <p>The encryption status of the snapshot depends on the values that you specify for <b>Encrypted</b>, <b>KmsKeyArn</b>, and <b>ParentSnapshotId</b>, and whether your Amazon Web Services account is enabled for <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#encryption-by-default"> encryption by default</a>. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebsapis-using-encryption.html"> Using encryption</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p> <important> <p>To create an encrypted snapshot, you must have permission to use the KMS key. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebsapi-permissions.html#ebsapi-kms-permissions"> Permissions to use Key Management Service keys</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p> </important>',
    )
    ParentSnapshotId: Optional[
        constr(pattern=r'^snap-[0-9a-f]+$', min_length=1, max_length=64)
    ] = Field(
        None,
        description='<p>The ID of the parent snapshot. If there is no parent snapshot, or if you are creating the first snapshot for an on-premises volume, omit this parameter.</p> <p>You can\'t specify <b>ParentSnapshotId</b> and <b>Encrypted</b> in the same request. If you specify both parameters, the request fails with <code>ValidationException</code>.</p> <p>The encryption status of the snapshot depends on the values that you specify for <b>Encrypted</b>, <b>KmsKeyArn</b>, and <b>ParentSnapshotId</b>, and whether your Amazon Web Services account is enabled for <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#encryption-by-default"> encryption by default</a>. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebsapis-using-encryption.html"> Using encryption</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p> <important> <p>If you specify an encrypted parent snapshot, you must have permission to use the KMS key that was used to encrypt the parent snapshot. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebsapi-permissions.html#ebsapi-kms-permissions"> Permissions to use Key Management Service keys</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p> </important>',
    )
    Tags: Optional[List[Tag]] = Field(
        None, description='The tags to apply to the snapshot.'
    )
    Timeout: Optional[conint(ge=10, le=4320)] = Field(
        None,
        description='<p>The amount of time (in minutes) after which the snapshot is automatically cancelled if:</p> <ul> <li> <p>No blocks are written to the snapshot.</p> </li> <li> <p>The snapshot is not completed after writing the last block of data.</p> </li> </ul> <p>If no value is specified, the timeout defaults to <code>60</code> minutes.</p>',
    )
    VolumeSize: conint(ge=1) = Field(
        ...,
        description='The size of the volume, in GiB. The maximum size is <code>65536</code> GiB (64 TiB).',
    )


class StartSnapshotRequest(BaseModel):
    ClientToken: Optional[IdempotencyToken] = None
    Description_1: Optional[Description] = Field(None, alias='Description')
    Encrypted: Optional[Boolean] = None
    KmsKeyArn_1: Optional[KmsKeyArn] = Field(None, alias='KmsKeyArn')
    ParentSnapshotId: Optional[SnapshotId] = None
    Tags_1: Optional[Tags] = Field(None, alias='Tags')
    Timeout_1: Optional[Timeout] = Field(None, alias='Timeout')
    VolumeSize_1: VolumeSize = Field(..., alias='VolumeSize')


class StartSnapshotResponse(BaseModel):
    BlockSize_1: Optional[BlockSize] = Field(None, alias='BlockSize')
    Description_1: Optional[Description] = Field(None, alias='Description')
    KmsKeyArn_1: Optional[KmsKeyArn] = Field(None, alias='KmsKeyArn')
    OwnerId_1: Optional[OwnerId] = Field(None, alias='OwnerId')
    ParentSnapshotId: Optional[SnapshotId] = None
    SnapshotId_1: Optional[SnapshotId] = Field(None, alias='SnapshotId')
    StartTime: Optional[TimeStamp] = None
    Status_1: Optional[Status] = Field(None, alias='Status')
    Tags_1: Optional[Tags] = Field(None, alias='Tags')
    VolumeSize_1: Optional[VolumeSize] = Field(None, alias='VolumeSize')
